import { createTool } from "@mastra/core";
import { z } from "zod";

import dotenv from "dotenv";
dotenv.config({ path: '/Users/alexandergirardet/Code/vibeflow-projects/seo-blogs/.env' });

// Direct function for use in workflows
export const sendSlackNotification = async (params: {
  webhookUrl: string;
  channel?: string;
  message: string;
}) => {
  const { webhookUrl, channel, message } = params;
  
  const payload = {
    text: message,
    ...(channel && { channel }),
  };

  try {
    const response = await fetch(webhookUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      throw new Error(`Slack API error: ${response.status} ${response.statusText}`);
    }

    return {
      success: true,
      message: "Notification sent successfully",
    };
  } catch (error) {
    throw new Error(`Failed to send Slack notification: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
};

// Format blog post notification message
export const formatBlogNotificationMessage = (params: {
  title: string;
  contentAngle: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  estimatedTrafficPotential: number;
  pullRequestUrl: string;
  fileUrl: string;
  githubOwner: string;
  githubRepo: string;
}) => {
  const {
    title,
    contentAngle,
    primaryKeyword,
    secondaryKeywords,
    estimatedTrafficPotential,
    pullRequestUrl,
    fileUrl,
    githubOwner,
    githubRepo,
  } = params;

  return `🚀 *New Blog Post Generated!*

📝 *Title:* ${title}

🎯 *Content Angle:* ${contentAngle}

🔍 *SEO Keywords:*
• Primary: "${primaryKeyword}"
• Secondary: ${secondaryKeywords.map(kw => `"${kw}"`).join(', ')}

📊 *Expected Traffic Potential:* ${estimatedTrafficPotential.toLocaleString()} monthly searches

🔗 *GitHub Pull Request:* ${pullRequestUrl}
📄 *File Location:* ${fileUrl}

✏️ *Next Steps:*
1. Review the blog post content in the PR
2. Make any necessary edits directly in GitHub or pull the branch locally
3. Once satisfied, merge the PR to trigger automatic deployment to Webflow
4. The blog will be live on your site after the Webflow deployment completes

⚡ *Quick Actions:*
• View PR: ${pullRequestUrl}
• Edit file: ${fileUrl}
• Repository: https://github.com/${githubOwner}/${githubRepo}

_Generated by your automated blog writing workflow_ 🤖`;
};

// Mastra tool for sending Slack notifications
export const sendSlackNotificationTool = createTool({
  id: "sendSlackNotification",
  description: "Send a notification message to a Slack channel via webhook",
  inputSchema: z.object({
    webhookUrl: z.string().describe("Slack webhook URL"),
    channel: z.string().optional().describe("Slack channel (optional if webhook is configured for specific channel)"),
    message: z.string().describe("Message to send to Slack"),
  }),
  outputSchema: z.object({
    success: z.boolean().describe("Whether the notification was sent successfully"),
    message: z.string().describe("Success or error message"),
  }),
  execute: async ({ context }) => {
    const { webhookUrl, channel, message } = context;
    return await sendSlackNotification({ webhookUrl, channel, message });
  },
});
